name: Mirror Dockerhub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: bellsoft/liberica-runtime-container
            repo: docker.io
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v4
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          crane copy docker.io/bellsoft/liberica-runtime-container:jdk-17-slim-glibc ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:jdk-17-slim-glibc
          crane copy docker.io/bellsoft/liberica-runtime-container:jre-17-slim-glibc ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:jre-17-slim-glibc